spring.application.name=HotelCloudGateway
server.port=8000
spring.main.web-application-type=reactive

# 8001: User-Service (G?p chung vào predicates[0])
spring.cloud.gateway.routes[0].id=user_service
spring.cloud.gateway.routes[0].uri=http://localhost:8001
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**,/api/customer/**,/api/customers/**

# 8002: Hotel-Service
spring.cloud.gateway.routes[1].id=hotel_service
spring.cloud.gateway.routes[1].uri=http://localhost:8002
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/hotels/**,/api/hotel-services/**,/api/hotel-amenities/**,/api/services/**

# 8003: Room-Service
spring.cloud.gateway.routes[2].id=room_service
spring.cloud.gateway.routes[2].uri=http://localhost:8003
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/rooms/**,/api/room-type/**

# 8004: Booking-Service
spring.cloud.gateway.routes[3].id=booking_service
spring.cloud.gateway.routes[3].uri=http://localhost:8004
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/bookings/**

# 8005: Search-Service
spring.cloud.gateway.routes[4].id=search_service
spring.cloud.gateway.routes[4].uri=http://localhost:8005
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/search/**

# 8006: Task-Service
spring.cloud.gateway.routes[5].id=task_service
spring.cloud.gateway.routes[5].uri=http://localhost:8006
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/tasks/**,/api/housekeeping/**,/api/maintenance/**

# CORS CONFIGURATION
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

logging.level.org.springframework.cloud.gateway=TRACE